
name: Deploy static front to Azure Web App - front-partiel-prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy static files to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'front-partiel-prod'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './'  # C’est ici que tu indiques le chemin vers index.html
>>>>>>> cf6f66d (corrigé yml)
